# Utilizar la imagen oficial de Node.js como base
FROM node:14
# Establecer el directorio de trabajo
WORKDIR /Back
# Copiar el package.json y el package-lock.json
COPY package*.json ./
# Instalar las dependencias
RUN npm install
# Copiar el resto de la aplicación
COPY . .
# Exponer el puerto en el que correrá el backend
EXPOSE 3001
CMD ["npm", "run", "start"]

